import Foundation
import MetaCodable

/// All user-driven mutations flow through this enum.
///
/// On iOS the View calls `appModel.dispatch(.toggleRead(id: ...))`
/// directly. On Android the same event is encoded as JSON, sent across
/// JNI as a single string argument to `appcoreDispatch(eventJSON:)`,
/// decoded on the Swift side, and dispatched through the same
/// `AppModel.dispatch` method. Adding a new mutation case here is the
/// only thing required to expose a new action to both platforms.
///
/// **Wire format:** an object with a `type` discriminator plus inline
/// payload fields. Examples:
///
/// ```json
/// {"type":"toggleRead","id":"39184235"}
/// {"type":"refresh"}
/// {"type":"setSearchQuery","value":"rust"}
/// ```
///
/// `Codable` is generated by [MetaCodable](https://github.com/SwiftyLab/MetaCodable).
/// `@CodedAt("type")` selects the discriminator key; the case name is used
/// as the discriminator value by default, and each case's labelled
/// associated values land as sibling keys at the top level. This shape
/// matches kotlinx.serialization's `Json { classDiscriminator = "type" }`
/// default, which is how `AppModelHolder.kt` configures its mirror — the
/// two sides agree without either writing custom (de)serialisation code.
@Codable
@CodedAt("type")
public enum AppEvent: Sendable, Equatable {
    case toggleRead(id: String)
    case markRead(id: String)
    case refresh
    case setSearchQuery(value: String)
}

extension AppEvent {
    private static let encoder = JSONEncoder()
    private static let decoder = JSONDecoder()

    public func toJSON() -> String {
        guard let data = try? Self.encoder.encode(self),
              let json = String(data: data, encoding: .utf8) else {
            return "{}"
        }
        return json
    }

    public init?(json: String) {
        guard let data = json.data(using: .utf8),
              let event = try? Self.decoder.decode(AppEvent.self, from: data) else {
            return nil
        }
        self = event
    }
}
