package com.example.appcore.state

import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.example.appcore.bridge.AppCoreAndroid
import com.example.appcore.bridge.CommandSink
import com.example.appcore.bridge.SnapshotSink
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.receiveAsFlow
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class Story(
    val id: String,
    val title: String,
    val author: String,
    val points: Int,
    val commentCount: Int,
    val url: String? = null,
    val createdAt: String,
    val isRead: Boolean = false,
)

@Serializable
data class AppState(
    val stories: List<Story> = emptyList(),
    val searchQuery: String = "",
    val isLoading: Boolean = false,
    val lastRefreshedAt: String? = null,
    val loadError: String? = null,
)

/**
 * Mirrors the Swift `AppEvent` enum. Wire shape is `{"type":"...", ...}`,
 * matching `AppCore/Sources/AppCore/AppEvent.swift`'s `@Codable` +
 * `@CodedAt("type")` MetaCodable annotations.
 */
@Serializable
sealed class AppEvent {
    @Serializable
    @SerialName("toggleRead")
    data class ToggleRead(val id: String) : AppEvent()

    @Serializable
    @SerialName("openStory")
    data class OpenStory(val id: String) : AppEvent()

    @Serializable
    @SerialName("refresh")
    data object Refresh : AppEvent()

    @Serializable
    @SerialName("setSearchQuery")
    data class SetSearchQuery(val value: String) : AppEvent()
}

/**
 * Mirrors the Swift `AppCommand` enum — the Core → UI direction. Wire
 * shape is `{"type":"...", ...}`, matching `AppCore/Sources/AppCore/AppCommand.swift`.
 *
 * Where `AppEvent` is the UI asking the core to mutate state, `AppCommand`
 * is the core asking the UI to perform a one-shot presentation that the
 * platform owns (Chrome Custom Tab, share sheet, etc.). Delivered through
 * `AppModelHolder.commands`.
 */
@Serializable
sealed class AppCommand {
    @Serializable
    @SerialName("presentURL")
    data class PresentURL(val value: String) : AppCommand()
}

/**
 * Process-wide holder for the model snapshot delivered from Swift.
 *
 * The Java surface is generated by `swift-java jextract --mode=jni` from
 * the Swift sources in `AppCoreAndroid`. `AppCoreAndroid` is the name of
 * the generated Java module class (named after the Swift module) and
 * exposes `appcoreCreate / appcoreDispatch / appcoreDestroy` as static
 * methods. All mutations are funnelled through `appcoreDispatch` with a
 * JSON-encoded `AppEvent`; adding a new mutation case in Swift is the
 * only thing required to expose a new action here.
 *
 * `SnapshotSink` is a Java interface jextract generated from the Swift
 * `protocol SnapshotSink` (because `enableJavaCallbacks: true` in
 * `swift-java.config`). We implement it directly on this object.
 *
 * **Why a singleton:** there is one `AppModel` per process on the Swift
 * side too. We initialise once from `AppCoreApplication.onCreate` and
 * leave it running for the process lifetime; the Compose tree just reads
 * `state`.
 *
 * **Loading state:** the snapshot's `isLoading` and `loadError` come
 * straight from Swift — no Kotlin-side timer. Pull-to-refresh's spinner
 * just observes `state.isLoading`.
 */
object AppModelHolder : SnapshotSink, CommandSink {
    var state by mutableStateOf<AppState?>(null)
        private set

    private val json = Json {
        classDiscriminator = "type"
        ignoreUnknownKeys = true
    }

    /**
     * One-shot commands from the Swift core to the UI. Channel-backed so
     * cold-start emissions (commands that fire before the screen-level
     * collector has attached) are buffered rather than dropped. The
     * single-event Channel.receiveAsFlow pattern is the canonical Compose
     * answer for "execute this once" — recomposition can't replay it.
     */
    private val _commands = Channel<AppCommand>(capacity = Channel.BUFFERED)
    val commands: Flow<AppCommand> get() = _commands.receiveAsFlow()

    fun start() {
        AppCoreAndroid.appcoreCreate(this, this)
    }

    /** Called from Swift via JNI on every Observations transaction. */
    override fun deliver(snapshotJSON: String) {
        state = json.decodeFromString<AppState>(snapshotJSON)
    }

    /** Called from Swift via JNI on every yield from `AppModel.commands`. */
    override fun deliverCommand(commandJSON: String) {
        val command = json.decodeFromString<AppCommand>(commandJSON)
        _commands.trySend(command)
    }

    fun dispatch(event: AppEvent) {
        AppCoreAndroid.appcoreDispatch(json.encodeToString(AppEvent.serializer(), event))
    }
}

@Composable
fun rememberAppModel(): AppModelHolder = AppModelHolder
