package com.example.appcore.state

import androidx.compose.runtime.*
import com.example.appcore.bridge.AppCoreAndroid
import com.example.appcore.bridge.SnapshotSink
import kotlinx.coroutines.delay
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class City(val id: String, val name: String, val country: String)

@Serializable
data class AppState(
    val cities: List<City>,
    val favorites: Set<String>,
    val globalFavoriteCount: Int,
    val lastRefreshedAt: String? = null
)

/**
 * Mirrors the Swift `AppEvent` enum. Wire shape is `{"type":"...", ...}`,
 * matching `AppCore/Sources/AppCore/AppEvent.swift`'s hand-rolled `Codable`.
 */
@Serializable
sealed class AppEvent {
    @Serializable
    @SerialName("toggleFavorite")
    data class ToggleFavorite(val id: String) : AppEvent()

    @Serializable
    @SerialName("refresh")
    data object Refresh : AppEvent()
}

/**
 * Process-wide holder for the model snapshot delivered from Swift.
 *
 * The Java surface is generated by `swift-java jextract --mode=jni` from
 * the Swift sources in `AppCoreAndroid`. `AppCoreAndroid` is the name of
 * the generated Java module class (named after the Swift module) and
 * exposes `appcoreCreate / appcoreDispatch / appcoreDestroy` as static
 * methods. All mutations are funnelled through `appcoreDispatch` with a
 * JSON-encoded `AppEvent`; adding a new mutation case in Swift is the
 * only thing required to expose a new action here.
 *
 * `SnapshotSink` is a Java interface jextract generated from the Swift
 * `protocol SnapshotSink` (because `enableJavaCallbacks: true` in
 * `swift-java.config`). We implement it directly on this object.
 *
 * **Why a singleton:** there is one `AppModel` per process on the Swift
 * side too. We initialise once from `AppCoreApplication.onCreate` and
 * leave it running for the process lifetime; the Compose tree just reads
 * `state`.
 */
object AppModelHolder : SnapshotSink {
    var state by mutableStateOf<AppState?>(null)
        private set
    var isRefreshing by mutableStateOf(false)
        private set

    private val json = Json {
        classDiscriminator = "type"
        ignoreUnknownKeys = true
    }

    fun start() {
        AppCoreAndroid.appcoreCreate(this)
    }

    /** Called from Swift via JNI on every Observations transaction. */
    override fun deliver(snapshotJSON: String) {
        state = json.decodeFromString<AppState>(snapshotJSON)
    }

    fun dispatch(event: AppEvent) {
        AppCoreAndroid.appcoreDispatch(json.encodeToString(AppEvent.serializer(), event))
    }

    fun toggleFavorite(id: String) = dispatch(AppEvent.ToggleFavorite(id))

    suspend fun refresh() {
        isRefreshing = true
        dispatch(AppEvent.Refresh)
        delay(1100)
        isRefreshing = false
    }
}

@Composable
fun rememberAppModel(): AppModelHolder = AppModelHolder
