package com.example.appcore.state

import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.example.appcore.bridge.AndroidCompletion
import com.example.appcore.bridge.AppCoreAndroid
import com.example.appcore.bridge.CommandSink
import com.example.appcore.bridge.IsLoadingSink
import com.example.appcore.bridge.SearchQuerySink
import com.example.appcore.bridge.SnapshotSink
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.receiveAsFlow
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class Story(
    val id: String,
    val title: String,
    val author: String,
    val points: Int,
    val commentCount: Int,
    val url: String? = null,
    val createdAt: String,
    val isRead: Boolean = false,
)

@Serializable
data class AppState(
    val stories: List<Story> = emptyList(),
    // searchQuery is intentionally absent — bridged per-property via
    // SearchQuerySink + BridgedSource. See AppModelHolder.searchQuery.
    val lastRefreshedAt: String? = null,
    val loadError: String? = null,
)

/**
 * Mirrors the Swift `AppEvent` enum. Wire shape is `{"type":"...", ...}`,
 * matching `AppCore/Sources/AppCore/AppEvent.swift`'s `@Codable` +
 * `@CodedAt("type")` MetaCodable annotations.
 *
 * `searchQuery` writes don't go through this enum — they ride a
 * dedicated per-property setter (`AppCoreAndroid.appcoreSetSearchQuery`)
 * with a matching `SearchQuerySink` push channel. Events stay the path
 * for command-shaped mutations (toggle, open, refresh).
 */
@Serializable
sealed class AppEvent {
    @Serializable
    @SerialName("toggleRead")
    data class ToggleRead(val id: String) : AppEvent()

    @Serializable
    @SerialName("openStory")
    data class OpenStory(val id: String) : AppEvent()

    @Serializable
    @SerialName("refresh")
    data object Refresh : AppEvent()
}

/**
 * Mirrors the Swift `AppCommand` enum — the Core → UI direction. Wire
 * shape is `{"type":"...", ...}`, matching `AppCore/Sources/AppCore/AppCommand.swift`.
 *
 * Where `AppEvent` is the UI asking the core to mutate state, `AppCommand`
 * is the core asking the UI to perform a one-shot presentation that the
 * platform owns (Chrome Custom Tab, share sheet, etc.). Delivered through
 * `AppModelHolder.commands`.
 */
@Serializable
sealed class AppCommand {
    @Serializable
    @SerialName("presentURL")
    data class PresentURL(val value: String) : AppCommand()
}

/**
 * Process-wide holder for the model snapshot delivered from Swift.
 *
 * The Java surface is generated by `swift-java jextract --mode=jni` from
 * the Swift sources in `AppCoreAndroid`. `AppCoreAndroid` is the name of
 * the generated Java module class (named after the Swift module) and
 * exposes `appcoreCreate / appcoreDispatch / appcoreDestroy` as static
 * methods. All mutations are funnelled through `appcoreDispatch` with a
 * JSON-encoded `AppEvent`; adding a new mutation case in Swift is the
 * only thing required to expose a new action here.
 *
 * `SnapshotSink` is a Java interface jextract generated from the Swift
 * `protocol SnapshotSink` (because `enableJavaCallbacks: true` in
 * `swift-java.config`). We implement it directly on this object.
 *
 * **Why a singleton:** there is one `AppModel` per process on the Swift
 * side too. We initialise once from `AppCoreApplication.onCreate` and
 * leave it running for the process lifetime; the Compose tree just reads
 * `state`.
 *
 * **Loading state:** `loadError` comes straight from Swift on the
 * snapshot. `isLoading` rides a per-property bridge instead — same
 * shape as `searchQuery`, exposed as [isLoading] below — so the
 * pull-to-refresh indicator and the empty-overlay flicker guard
 * fire on every fetch (search-typing debounce + explicit `.refresh`),
 * not just on the latter.
 */
object AppModelHolder : SnapshotSink, CommandSink, SearchQuerySink, IsLoadingSink {
    var state by mutableStateOf<AppState?>(null)
        private set

    /**
     * Per-property bridged `searchQuery`. Compose binds via
     * `holder.searchQuery.asState()`; user typing flows through
     * `BridgedSource.set` → `appcoreSetSearchQuery` → Swift (sync);
     * cold-start + programmatic Swift writes flow back via [deliver].
     * Reads come through JNI (`appcoreGetSearchQuery`) — no Kotlin-side
     * mirror — so Swift is the single source of truth. Echoes of
     * user-typed writes are suppressed on the Swift bridge actor's
     * `lastSetterValue` dedup so they never reach this sink.
     */
    val searchQuery = BridgedSource<String>(
        readThrough = AppCoreAndroid::appcoreGetSearchQuery,
        writeThrough = AppCoreAndroid::appcoreSetSearchQuery,
    )

    /**
     * Per-property bridged `isLoading`. Compose binds via
     * `holder.isLoading.asMutableState()` (same shape as
     * [searchQuery] for parity with `AndroidBinding`'s two-way
     * contract), but in practice the value is one-way Swift→Kotlin:
     * only `runFetch` writes it. Drives the pull-to-refresh indicator
     * and the empty-overlay flicker guard.
     */
    val isLoading = BridgedSource<Boolean>(
        readThrough = AppCoreAndroid::appcoreGetIsLoading,
        writeThrough = AppCoreAndroid::appcoreSetIsLoading,
    )

    private val json = Json {
        classDiscriminator = "type"
        ignoreUnknownKeys = true
    }

    /**
     * One-shot commands from the Swift core to the UI. Channel-backed so
     * cold-start emissions (commands that fire before the screen-level
     * collector has attached) are buffered rather than dropped. The
     * single-event Channel.receiveAsFlow pattern is the canonical Compose
     * answer for "execute this once" — recomposition can't replay it.
     */
    private val _commands = Channel<AppCommand>(capacity = Channel.BUFFERED)
    val commands: Flow<AppCommand> get() = _commands.receiveAsFlow()

    fun start() {
        AppCoreAndroid.appcoreCreate(this, this, this, this)
    }

    /** Called from Swift via JNI on every Observations transaction. */
    override fun deliver(snapshotJSON: String) {
        state = json.decodeFromString<AppState>(snapshotJSON)
    }

    /** Called from Swift via JNI on every yield from `AppModel.commands`. */
    override fun deliverCommand(commandJSON: String) {
        val command = json.decodeFromString<AppCommand>(commandJSON)
        _commands.trySend(command)
    }

    /**
     * Called from Swift via JNI when `state.searchQuery` changes — but
     * the bridge's `lastSetterValue` dedup filters echoes of writes
     * Compose just sent, so this fires only for the cold-start initial
     * value and genuine programmatic Swift writes.
     *
     * Uses a distinct method name from `SnapshotSink.deliver` because
     * Kotlin doesn't differentiate overloads by parameter name —
     * `deliver(String)` would conflict.
     */
    override fun deliverSearchQuery(value: String) {
        searchQuery.deliver(value)
    }

    /**
     * Called from Swift via JNI on every `state.isLoading` transition.
     * Bridge `lastSetterValue` dedup suppresses echoes of any
     * Compose-originated writes (in practice none — only `runFetch`
     * writes `isLoading`), so this fires on the cold-start emission
     * and every fetch start/finish.
     */
    override fun deliverIsLoading(value: Boolean) {
        isLoading.deliver(value)
    }

    fun dispatch(event: AppEvent) {
        AppCoreAndroid.appcoreDispatch(json.encodeToString(AppEvent.serializer(), event))
    }

    /**
     * Awaitable cousin of [dispatch] — mirrors iOS's
     * `AppEventDispatch.run(_:) async`. The coroutine suspends until
     * the Swift dispatch completes (the model's full `runFetch` for
     * `.refresh`, the synchronous reducer for the others).
     * Pull-to-refresh's onRefresh uses this so its indicator stays
     * visible for the actual fetch lifetime, not for the
     * snapshot-propagation race window. See [awaitWithCompletion] for
     * the underlying suspend/cancel shape.
     */
    suspend fun dispatchAwait(event: AppEvent) = awaitWithCompletion { completion ->
        AppCoreAndroid.appcoreDispatchAwait(
            json.encodeToString(AppEvent.serializer(), event),
            completion,
        )
    }
}

@Composable
fun rememberAppModel(): AppModelHolder = AppModelHolder

/**
 * Adapter from a JNI thunk that takes an [AndroidCompletion] parameter
 * to a Kotlin `suspend fun`. Wraps the thunk in a
 * `suspendCancellableCoroutine`; the coroutine resumes when the Swift
 * side fires `complete()`.
 *
 * Cancellation: if the calling coroutine is cancelled before the
 * completion fires, [AndroidCompletion.complete] resolves an inactive
 * continuation (which we silently drop). The Swift Task continues to
 * completion; for `.refresh` the in-flight fetch is cancel-and-replaced
 * internally by the next dispatch, so leaking is benign. Cross-language
 * cancellation is a future enhancement.
 *
 * Reusable for any awaitable JNI thunk shaped as `(args…, completion)`
 * — currently just [AppModelHolder.dispatchAwait], but the shape is
 * the same for any future awaitable bridge call.
 */
suspend inline fun awaitWithCompletion(
    crossinline thunk: (AndroidCompletion) -> Unit,
): Unit = suspendCancellableCoroutine { cont ->
    thunk(object : AndroidCompletion {
        override fun complete() {
            if (cont.isActive) cont.resume(Unit) { _, _, _ -> }
        }
    })
}
