package com.example.appcore.state

import androidx.compose.runtime.*
import com.example.appcore.bridge.AppCoreAndroid
import com.example.appcore.bridge.SnapshotSink
import kotlinx.coroutines.delay
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class City(val id: String, val name: String, val country: String)

@Serializable
data class Snapshot(
    val cities: List<City>,
    val favorites: Set<String>,
    val globalFavoriteCount: Int,
    val lastRefreshedAt: String? = null
)

/**
 * Compose-friendly state holder for AppState.
 *
 * The Java surface is generated by `swift-java jextract --mode=jni` from the
 * Swift sources in `AppCoreAndroid`. `AppCoreAndroid` is the name of the
 * generated Java module class (named after the Swift module) and exposes
 * `appcoreCreate/Toggle/Refresh/Destroy` as static methods.
 *
 * `SnapshotSink` is a Java interface jextract generated from the Swift
 * `protocol SnapshotSink` (because `enableJavaCallbacks: true` in
 * `swift-java.config`). We implement it directly on this holder.
 */
class AppStateHolder : SnapshotSink {
    private val handle: Long
    var snapshot by mutableStateOf<Snapshot?>(null)
        private set
    var isRefreshing by mutableStateOf(false)
        private set

    init {
        handle = AppCoreAndroid.appcoreCreate(this)
    }

    /** Called from Swift via JNI on every Observations transaction. */
    override fun deliver(snapshotJSON: String) {
        snapshot = Json.decodeFromString<Snapshot>(snapshotJSON)
    }

    fun toggleFavorite(id: String) {
        AppCoreAndroid.appcoreToggleFavorite(handle, id)
    }

    suspend fun refresh() {
        isRefreshing = true
        AppCoreAndroid.appcoreRefresh(handle)
        delay(1100)
        isRefreshing = false
    }

    fun close() {
        AppCoreAndroid.appcoreDestroy(handle)
    }
}

@Composable
fun rememberAppState(): AppStateHolder {
    val holder = remember { AppStateHolder() }
    DisposableEffect(holder) { onDispose { holder.close() } }
    return holder
}
