package com.example.appcore.state

import androidx.compose.runtime.*
import com.example.appcore.bridge.AppCoreAndroid
import com.example.appcore.bridge.SnapshotSink
import kotlinx.coroutines.delay
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class City(val id: String, val name: String, val country: String)

@Serializable
data class Snapshot(
    val cities: List<City>,
    val favorites: Set<String>,
    val globalFavoriteCount: Int,
    val lastRefreshedAt: String? = null
)

/**
 * Process-wide holder for AppState.
 *
 * The Java surface is generated by `swift-java jextract --mode=jni` from the
 * Swift sources in `AppCoreAndroid`. `AppCoreAndroid` is the name of the
 * generated Java module class (named after the Swift module) and exposes
 * `appcoreCreate/Toggle/Refresh/Destroy` as static methods.
 *
 * `SnapshotSink` is a Java interface jextract generated from the Swift
 * `protocol SnapshotSink` (because `enableJavaCallbacks: true` in
 * `swift-java.config`). We implement it directly on this object.
 *
 * **Why a singleton:** there is one `AppState` per process on the Swift
 * side too. We initialise once from `AppCoreApplication.onCreate` and
 * leave it running for the process lifetime; the Compose tree just reads
 * `snapshot`.
 */
object AppStateHolder : SnapshotSink {
    var snapshot by mutableStateOf<Snapshot?>(null)
        private set
    var isRefreshing by mutableStateOf(false)
        private set

    fun start() {
        AppCoreAndroid.appcoreCreate(this)
    }

    /** Called from Swift via JNI on every Observations transaction. */
    override fun deliver(snapshotJSON: String) {
        snapshot = Json.decodeFromString<Snapshot>(snapshotJSON)
    }

    fun toggleFavorite(id: String) {
        AppCoreAndroid.appcoreToggleFavorite(id)
    }

    suspend fun refresh() {
        isRefreshing = true
        AppCoreAndroid.appcoreRefresh()
        delay(1100)
        isRefreshing = false
    }
}

@Composable
fun rememberAppState(): AppStateHolder = AppStateHolder
