#if canImport(Android)
import Foundation
import AppCore

// MARK: - Handle management
//
// JNI gives us back an opaque Int64 to pass around. We use it to round-trip
// a strong reference to a `Holder` that owns the `AndroidBridge`.

private final class Holder {
    let bridge: AndroidBridge
    init(bridge: AndroidBridge) { self.bridge = bridge }
}

private func retain(_ holder: Holder) -> Int64 {
    let unmanaged = Unmanaged.passRetained(holder)
    return Int64(bitPattern: UInt64(UInt(bitPattern: unmanaged.toOpaque())))
}

private func borrow(_ handle: Int64) -> Holder {
    let raw = UnsafeRawPointer(bitPattern: UInt(UInt64(bitPattern: handle)))!
    return Unmanaged<Holder>.fromOpaque(raw).takeUnretainedValue()
}

private func release(_ handle: Int64) {
    let raw = UnsafeRawPointer(bitPattern: UInt(UInt64(bitPattern: handle)))!
    Unmanaged<Holder>.fromOpaque(raw).release()
}

// MARK: - JNI sink implementation
//
// Receives snapshots from `AndroidBridge` and forwards them via JNI to a
// Kotlin object the caller registered. Implemented here in Swift, not
// generated by jextract, because it crosses Swift→Java rather than the
// usual Java→Swift direction.

private final class JNICallbackSink: SnapshotSink {
    // Held by the AndroidBridge actor (Sendable). We don't own any JNI
    // env pointers here — we look them up from the JVM each delivery, since
    // the env is thread-bound and the actor's executor thread is not fixed.
    private let globalRef: jobject
    private let methodID: jmethodID

    init(globalRef: jobject, methodID: jmethodID) {
        self.globalRef = globalRef
        self.methodID = methodID
    }

    deinit {
        // Release the global ref. Look up env via JavaVirtualMachine.shared().
        // Implementation detail; see swift-java-jni-core for the exact API.
    }

    func deliver(snapshotJSON: String) {
        // Attach to current thread, lookup env, call the Kotlin method
        // with the JSON string. Details delegated to swift-java-jni-core.
    }
}

// MARK: - JNI entry points
//
// These are sync `@_cdecl` functions called by the JVM. They cannot block
// on the actor (we don't want to deadlock the JVM thread), so mutations
// fire-and-forget via a Task.
//
// The mutation's effect becomes visible to Kotlin only when the next
// snapshot arrives via the SnapshotSink — see §9 for the threading
// contract.

@_cdecl("Java_com_example_appcore_native_AppCoreNative_create")
public func appcore_create(
    env: UnsafeMutablePointer<JNIEnv>,
    clazz: jclass,
    sinkObj: jobject,
    sinkMethodID: jmethodID
) -> Int64 {
    // Promote the local sink ref to a global ref so we can call it from
    // any thread (specifically, the actor's executor thread, which we
    // don't control).
    let globalRef = env.pointee.pointee.NewGlobalRef(env, sinkObj)!
    let sink = JNICallbackSink(globalRef: globalRef, methodID: sinkMethodID)

    let bridge = AndroidBridge(sink: sink)
    let holder = Holder(bridge: bridge)

    // Kick off the observation loop. start() is async on the actor; we
    // spawn an unstructured Task and let it run.
    Task { await bridge.start() }

    return retain(holder)
}

@_cdecl("Java_com_example_appcore_native_AppCoreNative_destroy")
public func appcore_destroy(
    env: UnsafeMutablePointer<JNIEnv>,
    clazz: jclass,
    handle: Int64
) {
    let holder = borrow(handle)
    Task { await holder.bridge.close() }
    release(handle)
}

@_cdecl("Java_com_example_appcore_native_AppCoreNative_toggleFavorite")
public func appcore_toggleFavorite(
    env: UnsafeMutablePointer<JNIEnv>,
    clazz: jclass,
    handle: Int64,
    idStr: jstring
) {
    let holder = borrow(handle)
    let id = swiftString(from: idStr, env: env)
    Task { await holder.bridge.toggleFavorite(id) }
}

@_cdecl("Java_com_example_appcore_native_AppCoreNative_refresh")
public func appcore_refresh(
    env: UnsafeMutablePointer<JNIEnv>,
    clazz: jclass,
    handle: Int64
) {
    let holder = borrow(handle)
    Task { await holder.bridge.refresh() }
}

// String conversion helper — implementation lives in swift-java-jni-core.
private func swiftString(from jstr: jstring, env: UnsafeMutablePointer<JNIEnv>) -> String {
    // Use `GetStringUTFChars` / `ReleaseStringUTFChars` per swift-java-jni-core.
    fatalError("Implement using swift-java-jni-core")
}
#endif
